"use client";
import { useEffect, useState } from "react";

export default function PrivateCampaignParticipants({ campaignId }) {
  const [participants, setParticipants] = useState([]), [creatorId, setCreatorId] = useState(""), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [error, setError] = useState("");
  async function load() { setLoading(true); try { const r = await fetch(`/api/campaigns/${campaignId}/participants`); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d.error || "Could not load participants."); setParticipants(d.participants || []); } catch (e) { setError(e.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [campaignId]);
  async function change(method, id) { if (busy) return; setBusy(true); setError(""); setMessage(""); try { const r = await fetch(`/api/campaigns/${campaignId}/participants`, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify({ creatorId: id }) }); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d.error || "Could not update participant."); setCreatorId(""); setMessage(method === "POST" ? "Creator authorized." : "Creator access revoked."); await load(); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  return <section className="panel" style={{ marginTop: 18 }}><div className="panel-head"><h3>Private campaign access</h3></div><p className="brief">Authorize creators by their PulseFy creator ID.</p>{error && <div className="alert err">{error}</div>}{message && <p className="brief">{message}</p>}<form className="profile-form" onSubmit={(e) => { e.preventDefault(); change("POST", creatorId); }}><div className="field"><label>Creator ID</label><input required value={creatorId} onChange={(e) => setCreatorId(e.target.value)} placeholder="Creator ID" /></div><button className="btn btn-primary btn-sm" disabled={busy}>{busy ? "Saving…" : "Authorize creator"}</button></form>{loading ? <p className="brief">Loading participants…</p> : participants.length === 0 ? <p className="brief">No creators are authorized yet.</p> : <div style={{ marginTop: 12 }}>{participants.map((p) => <div className="brief" key={p.creatorId} style={{ padding: "8px 0", borderBottom: "1px solid var(--border)" }}><b>{p.name || p.username || "Creator"}</b> · {p.status} {p.status === "authorized" && <button type="button" className="btn btn-ghost btn-sm" disabled={busy} style={{ marginLeft: 8 }} onClick={() => change("DELETE", p.creatorId)}>Revoke</button>}</div>)}</div>}</section>;
}
