"use client";
import { useEffect, useState } from "react";
const LABEL = { open: "Open", under_review: "Under Review", awaiting_response: "Awaiting your response", resolved: "Resolved", dismissed: "Dismissed" };
export default function ReporterReports() {
  const [rows, setRows] = useState([]), [selected, setSelected] = useState(null), [message, setMessage] = useState(""), [evidence, setEvidence] = useState(""), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  async function load() { const r = await fetch("/api/reports?mine=1"); const d = await r.json().catch(() => ({})); if (r.ok) setRows(d.reports || []); else setError(d.error || "Could not load your reports."); }
  useEffect(() => { load(); }, []);
  async function open(id) { const r = await fetch(`/api/reports/${id}`); const d = await r.json().catch(() => ({})); if (r.ok) setSelected(d); else setError(d.error || "Could not load this report."); }
  async function respond(e) { e.preventDefault(); if (!selected) return; setBusy(true); const r = await fetch(`/api/reports/${selected.report.id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message, evidence }) }); const d = await r.json().catch(() => ({})); setBusy(false); if (!r.ok) { setError(d.error || "Could not send information."); return; } setMessage(""); setEvidence(""); await open(selected.report.id); await load(); }
  return <><p className="brief">Your reports are private. You can add information only when a reviewer requests it.</p>{error && <div className="alert err">{error}</div>}<div className="table-wrap"><table><thead><tr><th>Report ID</th><th>Reason</th><th>Status</th><th>Created</th></tr></thead><tbody>{rows.map((r) => <tr className="report-row" onClick={() => open(r.id)} key={r.id}><td><b>{r.id.slice(0,8).toUpperCase()}</b></td><td>{r.reason}</td><td><span className="status review">{LABEL[r.status]}</span></td><td>{new Date(r.createdAt).toLocaleDateString()}</td></tr>)}{!rows.length && <tr><td colSpan="4" className="brief">You have not submitted any reports.</td></tr>}</tbody></table></div>{selected && <div className="modal-overlay" onClick={() => setSelected(null)}><div className="modal report-detail" onClick={(e) => e.stopPropagation()}><div className="modal-head"><h3>Report {selected.report.id.slice(0,8).toUpperCase()}</h3><button className="modal-x" onClick={() => setSelected(null)}>×</button></div><p><b>{selected.report.reason}</b> · {LABEL[selected.report.status]}</p><p className="brief">{selected.report.description}</p>{selected.report.evidence && <p><a href={selected.report.evidence} target="_blank" rel="noreferrer">Open submitted evidence ↗</a></p>}{selected.report.status === "awaiting_response" && <form className="profile-form" onSubmit={respond}><div className="field"><label>Additional information *</label><textarea rows={4} value={message} onChange={(e) => setMessage(e.target.value)} minLength={10} required /></div><div className="field"><label>Additional evidence URL (optional)</label><input type="url" value={evidence} onChange={(e) => setEvidence(e.target.value)} placeholder="https://…" /></div><button className="btn btn-primary" disabled={busy}>{busy ? "Sending…" : "Send information"}</button></form>}<h4>Activity</h4>{selected.events.map((event) => <p className="brief" key={event.id}>{new Date(event.createdAt).toLocaleString()} · {event.action}{event.note ? ` — ${event.note}` : ""}</p>)}</div></div>}</>;
}
